//
//  PizzariaAppViewModelProtocol.swift
//  PizzariaApp-ios
//
//  Created by Ted Motta on 22/12/21.
//
//  This file was generated by the 🖤 Popcode's MVVM generator.
//

import Foundation

protocol PizzariaAppViewModelProtocol {
    var updateHelloWorld: ((String) -> Void)? { get set }
    func viewDidLoad()
}


