//
//  PizzariaAppViewController.swift
//  PizzariaApp-ios
//
//  Created by Eduardo Yamagata on 17/12/21.
//
//  This file was generated by the 🖤 Popcode's MVVM generator.
//

import UIKit

final class PizzariaAppViewController: UIViewController {
    // MARK: - Outlets
    private lazy var logoImageView: UIImageView = {
        let imageView = UIImageView(frame: .zero)
        imageView.translatesAutoresizingMaskIntoConstraints = false
        imageView.image = UIImage(named: "PizzaLogo")
        return imageView
    }()
    
    // MARK: - Class properties
    private var viewModel: PizzariaAppViewModelProtocol

    // MARK: - Public properties

    
    // MARK: - Life Cycle
    init(viewModel: PizzariaAppViewModelProtocol = PizzariaAppViewModel()) {
        self.viewModel = viewModel
        super.init(nibName: nil, bundle: nil)
    }
    
    required init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        setupSubViews()
        bindUI()
        viewModel.viewDidLoad()
    }
    
    // MARK: - Class Configurations
    private func setupSubViews() {
        view.addSubview(logoImageView)
        logoImageView.centerXAnchor.constraint(equalTo: view.centerXAnchor).isActive = true
        logoImageView.centerYAnchor.constraint(equalTo: view.centerYAnchor).isActive = true
    }
    
    // MARK: - UIActions
    private func bindUI() {  }
    
    // MARK: - Class Methods
}
