//
//  PizzariaAppViewModel.swift
//  PizzariaApp-ios
//
//  Created by Ted Motta on 17/12/21.
//
//  This file was generated by the 🖤 Popcode's MVVM generator.
//

import UIKit

final class PizzariaAppViewModel {
    private enum Strings {
        static let helloWorld = "Hello, World!"
    }
    
    var updateHelloWorld: ((String) -> Void)?
    
    func viewDidLoad() {
        updateHelloWorld?(Strings.helloWorld)
    }
}

extension PizzariaAppViewModel: PizzariaAppViewModelProtocol {  }
