//
//  PizzariaAppViewModel.swift
//  PizzariaApp-ios
//
//  Created by Ted Motta on 17/12/21.
//
//  This file was generated by the 🖤 Popcode's MVVM generator.
//

import UIKit

final class PizzariaAppViewModel {
    // MARK: - Components
    public var stringImage: String {
        return "pizza-logo-design_9845-319"
    }
    
    // MARK: - Methods
    init() {}
}
